id = "poor-mans-tsql-lsp"
name = "Poor Man's T-SQL Formatter"
version = "0.1.0"
schema_version = 1
description = "Format SQL Server scripts with Poor Man's T-SQL Formatter."
authors = ["Onța Nicolae"]
repository = "https://github.com/chadnicu/zed-tsql-tools"
capabilities = [{ kind = "npm:install", package = "@onta.nicolae/tsql-tools" }]

[language_servers.poor-mans-tsql-lsp]
name = "Poor Man's T-SQL Formatter"
languages = ["SQL"]
